#include "hbdefs.h"

#ifdef HB_LEGACY_LEVEL4
HB_FUNC_TRANSLATE( TIP_FILEMIMETYPE, HB_MIMEFILE )
HB_FUNC_TRANSLATE( TIP_FILENAMEMIMETYPE, HB_MIMEFNAME )
HB_FUNC_TRANSLATE( TIP_MIMETYPE, HB_MIMESTR )
#endif
